plugins {
    id "architectury-plugin" version "3.4.164"
    id "dev.architectury.loom" version "1.9-SNAPSHOT" apply false
    id "org.jetbrains.kotlin.jvm" version "2.3.21" apply false

}

architectury {
    minecraft = rootProject.minecraft_version
}

subprojects {
    apply plugin: "dev.architectury.loom"
    apply plugin: "org.jetbrains.kotlin.jvm"

    loom {
        silentMojangMappingsLicense()
    }

    repositories {
        maven {
            name = 'ParchmentMC'
            url = 'https://maven.parchmentmc.org'
        }
    }

    dependencies {
        minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
        mappings loom.officialMojangMappings()

    }

    sourceSets.main.kotlin.srcDirs += "src/main/java"
    sourceSets.main.resources.srcDirs += "src/generated/resources"

    kotlin {
        jvmToolchain(21)
    }
}

allprojects {
    apply plugin: "java"
    apply plugin: "architectury-plugin"
    apply plugin: "maven-publish"

    base {
        archivesName = rootProject.archives_base_name
    }

    version = rootProject.mod_version
    group = rootProject.maven_group

    repositories {
        // Add repositories to retrieve artifacts from in here.
        // You should only use this when depending on other mods because
        // Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
        // See https://docs.gradle.org/current/userguide/declaring_repositories.html
        // for more information about repositories.
        mavenCentral()
        maven {
            url "https://maven.blamejared.com"
        }
        maven {
            url "https://maven.squiddev.cc"
        }
        maven { url "https://maven.shedaniel.me/" }
        maven { url "https://maven.terraformersmc.com/releases/" }
        maven { url = "https://mvn.devos.one/snapshots/" }
        maven { url 'https://jitpack.io' }
        maven {
            name = "Modrinth"
            url = "https://api.modrinth.com/maven"
        }
        //maven { url = "https://maven.jamieswhiteshirt.com/libs-release/" }
        maven { url = "https://maven.nucleoid.xyz/" } // Common Protection API
        //maven { url = "https://maven.jamieswhiteshirt.com/libs-release/" } // Entity Reach Attribute
        maven { url = "https://cfa2.cursemaven.com" }
        maven { url = "https://repo.unascribed.com" } // Ears API
        maven { url = "https://maven.enginehub.org/repo/" } // world edit
        maven { url "https://maven.neoforged.net/releases/" }
    }

    tasks.withType(JavaCompile) {
        options.encoding = "UTF-8"
        options.release = 21
    }

    java {
        toolchain.languageVersion = JavaLanguageVersion.of(21)
        withSourcesJar()
    }
}
